### PR TITLE
Convert ddmm.mmmm to -ddd.dddddd for consistency.

### PR DESCRIPTION
**Pull request by mathieucarbou**
Ref: https://github.com/vshymanskyy/TinyGSM/pull/365/commits/9751b6011ac9f840a3371d5aa50b90f48360728d

This PR is a proposal for a breaking change in returned GPS data.

Such change was done by @SRGDamia1 4 years ago in the original fork in commit https://github.com/vshymanskyy/TinyGSM/pull/365/commits/9751b6011ac9f840a3371d5aa50b90f48360728d for SIM7600.

It was also done (but not so precisely) by @eclipse95 in his fork here: https://github.com/lewisxhe/TinyGSM/compare/master...eclipse95:TinyGSM:patch-1 for the A7670.

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@lewisxhe : this PR contains some changes to fix the lat / long to be consistent with the changes already in TinyGSM (see PR description. Only the second commit is relevant to this change, first commit being the CI addition. CI results can be seen in my fork here: https://github.com/mathieucarbou/lewisxhe-TinyGSM/actions

Please note that I didn't / was not able to test.

Thanks!

**Comment by lewisxhe** [comment]
I cannot merge this PR because the longitude and latitude formats output by A7670 and A7608 can be used directly without calculation.

**Comment by mathieucarbou** [comment]
Ok! So in that cas we can cleanup the unused variables triggering a warning. I will update the PR later once I will be able to confirm that with the module (still not received).

**Comment by mathieucarbou** [comment]
Closing - will open a PR to cleanup warning

**Pull request closed without merging**
